-- Insert 31 new personnel records
INSERT INTO public.personnel (
  last_name, first_name, classification, badge_number, division,
  regular_pay, premiums, overtime, payout, other_pay, health_dental_vision
) VALUES
('Andrade', 'Roland', NULL, '2941', 'Chief''s Office', NULL, NULL, NULL, NULL, NULL, NULL),
('Bell', 'Tanner', NULL, '3656', 'Metropolitan Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Buchanan', 'Dorin', NULL, '3398', 'Metropolitan Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Cofer', 'Craig', NULL, '3626', 'Operations Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Elms', 'Charles', NULL, '2616', 'Investigations', NULL, NULL, NULL, NULL, NULL, NULL),
('Esparza', 'Enrique', NULL, '2455', 'Investigations', NULL, NULL, NULL, NULL, NULL, NULL),
('Gonzalez', 'Jose', NULL, '2593', 'Field Operations', NULL, NULL, NULL, NULL, NULL, NULL),
('Gutierrez', 'Frank', NULL, '3175', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Gutierrez', 'Martin', NULL, '3652', 'Operations Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Hernandez', 'Gilbert', NULL, '2901', 'Operations Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Landaverde', 'Walmer', NULL, 'R372', 'Academy', NULL, NULL, NULL, NULL, NULL, NULL),
('Liggett', 'Tyler', NULL, '3488', 'Metropolitan Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Lizardi', 'Oscar', NULL, '2629', 'Training/Human Resources', NULL, NULL, NULL, NULL, NULL, NULL),
('Lopez', 'Jorge', NULL, '3029', 'Chief''s Office', NULL, NULL, NULL, NULL, NULL, NULL),
('Lopez', 'Maria', NULL, '3200', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Lopez', 'Nelly', NULL, '3813', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Marshall', 'Patrick', NULL, '3448', 'Metropolitan Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Marty', 'Joseph', NULL, '2942', 'Traffic', NULL, NULL, NULL, NULL, NULL, NULL),
('McKee', 'Jonathan', NULL, '3467', 'Metropolitan Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Moreno', 'Manuel', NULL, '2837', 'Homeland Security', NULL, NULL, NULL, NULL, NULL, NULL),
('Ponce De Leon', 'Rosa', NULL, '2866', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Puentes', 'Andres', NULL, 'R366', 'Academy', NULL, NULL, NULL, NULL, NULL, NULL),
('Ramsey', 'Amber', NULL, '3800', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Rodriguez', 'Julian', NULL, '2836', 'Operations Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Rodriguez', 'Robert', NULL, '2755', 'Chief''s Office', NULL, NULL, NULL, NULL, NULL, NULL),
('Ruelas', 'Charles', NULL, '3824', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Ruelas', 'Jose', NULL, '3795', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Sanchez', 'Lorenzo', NULL, '3783', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL),
('Santaella', 'Robert', NULL, '3717', 'Operations Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Sorenson', 'Mathew', NULL, '2700', 'Metropolitan Division', NULL, NULL, NULL, NULL, NULL, NULL),
('Weber', 'Richard', NULL, '2566', 'Patrol', NULL, NULL, NULL, NULL, NULL, NULL);

-- Verify the insertion
SELECT COUNT(*) as inserted_count FROM personnel WHERE badge_number IN (
  '2941',
  '3656',
  '3398',
  '3626',
  '2616',
  '2455',
  '2593',
  '3175',
  '3652',
  '2901',
  'R372',
  '3488',
  '2629',
  '3029',
  '3200',
  '3813',
  '3448',
  '2942',
  '3467',
  '2837',
  '2866',
  'R366',
  '3800',
  '2836',
  '2755',
  '3824',
  '3795',
  '3783',
  '3717',
  '2700',
  '2566'
);
